language: ruby

rvm:
  - jruby
  - rbx-2
  - 2.3
  - 2.4
  - 2.5
  - 2.6

bundler_args: --without development

sudo: false

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: 2.5
    - rvm: 2.6

notifications:
  emails: false
